version: '3.4'

volumes:
  postgres-data:
  mailpit-data:

services:

  postgres:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    env_file:
      - .env

  mailpit:
    image: axllent/mailpit:latest
    restart: always
    ports:
      - 5000:8025
      - 1025:1025
    volumes:
      - mailpit-data:/data
